spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:${MYSQL_HOST_PORT:13306}/ecommerce?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ecommerce}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ecommerce-local}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
